[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor = "9RH1AhdbihXmBkkmMD6HaoHQz9LECwv9rL3E1s8VVqPS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jimii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
